version: '>= 0.14.0'

formatter: markdown table

content: |-
  # Terraform Intersight UCS Domain Profiles
  Manages Intersight UCS Domain Profiles
  
  Location in GUI:
  `Profiles` » `UCS Domain Profiles` » `Create UCS Domain Profiles`
  
  ## Example

  ### main.tf
  ```hcl
  {{ include "examples/complete/main.tf" }}
  ```

  ### provider.tf
  ```hcl
  {{ include "examples/complete/provider.tf" }}
  ```

  ### variables.tf
  ```hcl
  {{ include "examples/complete/variables.tf" }}
  ```

  ## Environment Variables

  ### Terraform Cloud/Enterprise - Workspace Variables
  - Add variable apikey with value of [your-api-key]
  - Add variable secretkey with value of [your-secret-file-content]

  ### Linux
  ```bash
  export TF_VAR_apikey="<your-api-key>"
  export TF_VAR_secretkey=`cat <secret-key-file-location>`
  ```

  ### Windows
  ```bash
  $env:TF_VAR_apikey="<your-api-key>"
  $env:TF_VAR_secretkey="<secret-key-file-location>""
  ```


  {{ .Requirements }}
  {{ .Providers }}
  {{ .Inputs }}
  {{ .Outputs }}
  {{ .Resources }}
output:
  file: README.md
  mode: replace

sort:
  enabled: false